### PR TITLE
README updates

### PR DESCRIPTION
**Pull request by adamchainz**
* HTTPS link to readthedocs
* Syntax highlighting

### CODE REVIEW

**Comment by ubernostrum** [comment]
Could you change `code-block` to `code`? I don't like relying on the Sphinx-specific directive in a README, since it may get rendered in places that don't understand that one (while `code` is a standard reStructuredText directive).

**Comment by adamchainz** [comment]
TIL, I'd always been under the impression code-block was universal, as docutils and github render it fine alongside sphinx.

**Comment by ubernostrum** [comment]
I think this is obsolete now?

**Comment by adamchainz** [comment]
yes you did it in 3596fa14de8b0d2937f79692a5811ac64061fa46

**Pull request closed without merging**
